name: Build Component Library, Docs
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install 🔧
        run: |
          npm install

      - name: Build App 🔧
        run: |
          npm run build
      - name: Build Docs 🔧
        run: |
          npm run 
  
