name: Publish Storybook and Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  publish-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install 🔧
        run: |
          npm install

      - name: Build Docs 🔧
        run: |
          npm run build-docs

      - name: "Upload Docs"
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

      - name: Build Storybook 🔧
        run: |
          npm run build-storybook

      - name: "Upload Storybook"
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: storybook-static

      - name: "Generate Coverage Report"
        run: |
          npm run test

      - name: "Upload Coverage Report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      
      - name: Download all Artifacts 🚀
        if: always()
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: artifacts

      - name: List all artifacts 🚀
        if: always()
        run: |
          ls -la artifacts



     